insert into INMOBILIARIA (id, nombre, email, telefono) values ( NEXTVAL('hibernate_sequence'), 'idealista', ' redaccion@idealista.com', '+ (34) 91 788 34 31.');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'Melibero', 'rgpd@catrealestate.com', '934.671.115');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'HomeSeller', 'enquiry@homeseller.sg', '+65 9221 2291');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'Habitat', 'redaccion@habitat.com', '(+34) 912 170 531 ');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'real', 'social@housfy.com', '911 23 79 75');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'Housfy', 'dbeeken5@example.com', '233-784-0316');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'MELIBERO', 'pmenichelli6@behance.net', '587-400-9614');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'netHousers', 'pbuyers7@apple.com', '165-772-3261');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'TIKO', 'jwyllis8@drupal.org', '994-537-6976');
insert into INMOBILIARIA (id, nombre, email, telefono) values (NEXTVAL('hibernate_sequence'), 'PROPERTISTA', 'spughsley9@ow.ly', '946-811-6447');
